[package]
name = "repository_tree_creator"
version = "0.1.0"
edition = "2021"

[dependencies]
ctor = "0.2.8"
diff = "0.1.13"
dit_id_generator = { git = "https://github.com/divinoschaeffer/dit_id_generator.git" }